/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author lully
 */
public class Tela3 extends javax.swing.JFrame {
    
     // Método para carregar dados do banco na tabela
    public void carregarDadosTabela() {
        
        TabelaPreenchimento tabelaPreenchimento = new TabelaPreenchimento();
        tabelaPreenchimento.preencherTabela(impressoras); // tabelaDados é o nome da sua tabela na interface
        
        // Obtém o modelo da tabela para manipular as linhas
        DefaultTableModel model = (DefaultTableModel) impressoras.getModel();
        
         // Limpa dados antigos da tabela para evitar duplicações
        model.setRowCount(0);
        
        // Conecta ao banco de dados e busca dados
        
        try {
            // Obtenha a conexão da classe ConexaoBanco
            Connection conn = (Connection) ConexaoBanco.getConexao(); // Aqui, use o método correto da sua classe de conexão
            
            // Defina a consulta SQL para obter dados
            String sql = "SELECT id, nome_impressora, local_impressora, toner, modelo_toner, quantidade FROM impressoras";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            
            // Adiciona os dados do ResultSet no modelo da tabela
            while (rs.next()) {
                Object[] linha = {
                    rs.getObject("Id"),
                    rs.getObject("nome_impressora"),
                    rs.getObject("local_impressora"),
                    rs.getObject("toner"),
                    rs.getObject("modelo_toner"),
                    rs.getObject("quantidade")
                };
                model.addRow(linha); // Adiciona a linha ao modelo da tabela
            }
            
            // Fecha a conexão se necessário
            rs.close();
            stmt.close();
            conn.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erro ao carregar dados do banco na tabela.");
        }
        
        
        
        }
        
    


    /**
     * Creates new form Tela3
     */
    public Tela3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CarregarDados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        impressoras = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, 250, 60));

        CarregarDados.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CarregarDados.setText("Carregar Dados");
        CarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(CarregarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 300, 60));

        impressoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Local", "Toner]", "Modelo", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(impressoras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 1080, 330));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Impressoras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ceu.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarDadosActionPerformed
        // TODO add your handling code here:
        CarregarDados.addActionListener(e -> carregarDadosTabela());
    }//GEN-LAST:event_CarregarDadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tela1 tela1 = new Tela1();
        tela1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarregarDados;
    private javax.swing.JTable impressoras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
